Add -fgnu89-inline to CFLAGS
In GCC 5.1 default C standard changed to -std=gnu11. This changed behavior of
inline functions. Build error is:
[  130s] /home/abuild/rpmbuild/BUILD/libmm-fileinfo-0.6.3/utils/.libs/libmmfile_utils.so: undefined reference to `mmfile_io_le_uint32'
[  130s] collect2: error: ld returned 1 exit status

Changing back to gnu89 inlining mode fixes the issue.

Change-Id: I782c77d07620d952bfa13f9bee7dcc332521133b
Signed-off-by: Yury Usishchev <y.usishchev@samsung.com>